services:
  db:
    image: "docker.io/postgres:16.3-alpine"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - ${DB_PORT}:5432
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: "docker.io/redis:7.4.0-alpine"
    ports:
      - ${REDIS_PORT}:6379
    command:
      - --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped

volumes:
  postgres:
